version: "3"

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: katzen-postgres
    hostname: postgres
    env_file: ./.env
    volumes:
      - katzen-data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - 2345:5432

volumes:
  katzen-data:
    external: true
